force-app/main/default/objects/office_chat__e/office_chat__e.object-meta.xml
<CustomObject>
    <label>office chat</label>
    <pluralLabel>office chats</pluralLabel>
</CustomObject>

force-app/main/default/objects/office_chat__e/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/office_player__e/office_player__e.object-meta.xml
<CustomObject>
    <label>office player</label>
    <pluralLabel>office players</pluralLabel>
</CustomObject>

force-app/main/default/objects/office_player__e/fields/moveSignal__c.field-meta.xml
<CustomField>
    <fullName>moveSignal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this event is to signal a player move</description>
    <label>moveSignal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlayerEventTest.cls
/*******************************************************************************************
 * @Name         PlayerEventTest
 * @Author       Damien Fleminks
 * @Description  Test class to evaluate the outcomes og the methods in the PlayerEvent class
 *******************************************************************************************/

@isTest
private class PlayerEventTest {
  @isTest
  static void publishPlayerTest() {
    office_player__e pEvent = new office_player__e(moveSignal__c = true);
    System.assert(PlayerEvent.publishPlayer(pEvent));
  }

  @isTest
  static void publishChatTest() {
    office_chat__e pEvent = new office_chat__e(
      message__c = 'This is a test message'
    );
    System.assert(PlayerEvent.publishChat(pEvent));
  }
}