force-app/main/default/objects/Office_Play_config__c/Office_Play_config__c.object-meta.xml
<CustomObject>
    <label>Office Play Config</label>
    <nameField>
        <label>Office Play Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Play Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Office_Play_Config__c.field-meta.xml
<CustomField>
    <fullName>Office_Play_Config__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office Play Config</label>
    <referenceTo>Office_Play_config__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PlayerUtilityTest.cls
/*******************************************************************************************
 * @Name         PlayerUtilityTest
 * @Author       Damien Fleminks
 * @Description  Test class to evaluate the outcomes og the methods in the PlayerUtility class
 *******************************************************************************************/

@isTest
private class PlayerUtilityTest {
  /**
   *  A testSetup method to setup test data that will be reused by multiple test methods
   *  We will test one Office_Play_Config__c record with and one without a player
   */
  @testSetup
  static void setup() {
    String userId = UserInfo.getUserId();
    Office_Play_Config__c office1 = new Office_Play_Config__c(
      Name = 'TestOffice1'
    );
    Office_Play_Config__c office2 = new Office_Play_Config__c(
      Name = 'TestOffice2'
    );
    insert office1;
    insert office2;
    Player__c player = new Player__c(
      Name = 'TestPlayer',
      User__c = userId,
      Office_Play_Config__c = office1.Id
    );
    insert player;
  }
  /**
   *  This method tests the different outcomes for the getPlayer() method
   */
  @isTest
  static void getPlayerTest() {
    String userId = UserInfo.getUserId();
    Office_Play_Config__c office = [
      SELECT Id
      FROM Office_Play_Config__c
      WHERE Name = 'TestOffice1'
      LIMIT 1
    ];
    Player__c player = PlayerUtility.getPlayer(office.Id);
    System.assertEquals(userId, player.User__c);
    Player__c player2 = PlayerUtility.getPlayer('dont exists');
    System.assertEquals(null, player2);
  }

  @isTest
  static void createPlayerTest() {
    String userId = UserInfo.getUserId();
    Office_Play_Config__c office = [
      SELECT Id
      FROM Office_Play_Config__c
      WHERE Name = 'TestOffice1'
      LIMIT 1
    ];
    Office_Play_Config__c office2 = [
      SELECT Id
      FROM Office_Play_Config__c
      WHERE Name = 'TestOffice2'
      LIMIT 1
    ];
    Player__c player = [
      SELECT Id
      FROM Player__c
      WHERE
        User__c = :userId
        AND Name = 'TestPlayer'
        AND Office_Play_Config__c = :office.Id
      LIMIT 1
    ];
    Player__c playerTest1 = PlayerUtility.createPlayer(
      'TestPlayer',
      'p1',
      office.Id
    );
    Player__c playerTest2 = PlayerUtility.createPlayer(
      'TestPlayer2',
      'p1',
      office2.Id
    );
    System.assertEquals(player.Id, playerTest1.Id);
    System.assert(player.Id != playerTest2.Id);
  }
}